export const projects = [
	{
		header: 'Computapars',
		text: `A personal design system monorepo. Created with Storybook, 
		Styled Components and Grommet, Computapars makes it easy to scale out my personal projects.`,
		href: 'computpars',
		hoverTag: 'View Project',
		bgImage: false,
		bgColor: '#ff5454',
	},
	{
		header: 'Sound Reverie',
		text: `A blog exploring sound and inpsirations. `,
		href: 'sound-reverie',
		hoverTag: 'View Project',
		bgImage: false,
		bgColor: '#007503',
	},
	{
		header: 'Yourturn.dev',
		text: `Task sharing makes my home run efficiently.`,
		href: 'yourturn-dev',
		hoverTag: 'View Project',
		bgImage: false,
		bgColor: '#29335c',
	},
	// {
	// 	header: '4',
	// 	text: `Nobody likes to wait… but you can make it less of a pain. I've created.`,
	// 	href: 'foo-bar',
	// 	hoverTag: 'View Project',
	// 	bgImage: 'carol-e1449867374669.jpg',
	// 	bgColor: 'yellow',
	// },
	// {
	// 	header: '5',
	// 	text: `Nobody likes to wait… but you can make it less of a pain. I've created.`,
	// 	href: 'foo-bar',
	// 	hoverTag: 'View Project',
	// 	bgImage: 'carol-e1449867374669.jpg',
	// 	bgColor: 'yellow',
	// },
	// {
	// 	header: '6',
	// 	text: `Nobody likes to wait… but you can make it less of a pain. I've created.`,
	// 	href: 'foo-bar',
	// 	hoverTag: 'View Project',
	// 	bgImage: false,
	// 	bgColor: 'pink',
	// },
	// {
	// 	header: '7',
	// 	text: `Nobody likes to wait… but you can make it less of a pain. I've created.`,
	// 	href: 'foo-bar',
	// 	hoverTag: 'View Project',
	// 	bgImage: false,
	// 	bgColor: 'blue',
	// },
	// {
	// 	header: '8',
	// 	text: `Nobody likes to wait… but you can make it less of a pain. I've created.`,
	// 	href: 'foo-bar',
	// 	hoverTag: 'View Project',
	// 	bgImage: false,
	// 	bgColor: 'white',
	// },
	// {
	// 	header: '9',
	// 	text: `Nobody likes to wait… but you can make it less of a pain. I've created.`,
	// 	href: 'foo-bar',
	// 	hoverTag: 'View Project',
	// 	bgImage: 'carol-e1449867374669.jpg',
	// 	bgColor: 'yellow',
	// },
	// {
	// 	header: '10',
	// 	text: `Nobody likes to wait… but you can make it less of a pain. I've created.`,
	// 	href: 'foo-bar',
	// 	hoverTag: 'View Project',
	// 	bgImage: 'carol-e1449867374669.jpg',
	// 	bgColor: 'yellow',
	// },
];
