export const projects = [
	{
		header: 'foo',
		text: `Nobody likes to wait… but you can make it less of a pain. I've created.`,
		href: 'foo-bar',
		hoverTag: 'View Project',
		bgImage: false,
		bgColor: 'pink',
	},
	{
		header: 'bar',
		text: `Nobody likes to wait… but you can make it less of a pain. I've created.`,
		href: 'foo-bar',
		hoverTag: 'View Project',
		bgImage: false,
		bgColor: 'blue',
	},
	{
		header: 'baz',
		text: `Nobody likes to wait… but you can make it less of a pain. I've created.`,
		href: 'foo-bar',
		hoverTag: 'View Project',
		bgImage: false,
		bgColor: 'white',
	},
	{
		header: 'fi',
		text: `Nobody likes to wait… but you can make it less of a pain. I've created.`,
		href: 'foo-bar',
		hoverTag: 'View Project',
		bgImage: 'carol-e1449867374669.jpg',
		bgColor: 'yellow',
	},
	{
		header: 'fum',
		text: `Nobody likes to wait… but you can make it less of a pain. I've created.`,
		href: 'foo-bar',
		hoverTag: 'View Project',
		bgImage: 'carol-e1449867374669.jpg',
		bgColor: 'yellow',
	},
	{
		header: 'foo',
		text: `Nobody likes to wait… but you can make it less of a pain. I've created.`,
		href: 'foo-bar',
		hoverTag: 'View Project',
		bgImage: false,
		bgColor: 'pink',
	},
	{
		header: 'bar',
		text: `Nobody likes to wait… but you can make it less of a pain. I've created.`,
		href: 'foo-bar',
		hoverTag: 'View Project',
		bgImage: false,
		bgColor: 'blue',
	},
	{
		header: 'baz',
		text: `Nobody likes to wait… but you can make it less of a pain. I've created.`,
		href: 'foo-bar',
		hoverTag: 'View Project',
		bgImage: false,
		bgColor: 'white',
	},
	{
		header: 'fi',
		text: `Nobody likes to wait… but you can make it less of a pain. I've created.`,
		href: 'foo-bar',
		hoverTag: 'View Project',
		bgImage: 'carol-e1449867374669.jpg',
		bgColor: 'yellow',
	},
	{
		header: 'fum',
		text: `Nobody likes to wait… but you can make it less of a pain. I've created.`,
		href: 'foo-bar',
		hoverTag: 'View Project',
		bgImage: 'carol-e1449867374669.jpg',
		bgColor: 'yellow',
	},
];
