export const featuredProjects = [
	{
		header: 'Computapars',
		text: `A personal design system monorepo. Created with Storybook, 
		Styled Components and styled-system, Computapars makes it easy to scale out my personal projects.`,
		href: 'computpars',
		hoverTag: 'View Project',
		bgImage: false,
		bgColor: '#ff5454',
		useDivider: true,
	},
	{
		header: 'Sound Reverie',
		text: `A blog exploring sound and inpsirations. `,
		href: 'sound-reverie',
		hoverTag: 'View Project',
		bgImage: false,
		bgColor: '#007503',
		useDivider: true,
	},
	{
		header: 'Yourturn.dev',
		text: `Task sharing makes my home run efficiently.`,
		href: 'yourturn-dev',
		hoverTag: 'View Project',
		bgImage: 'carol-e1449867374669.jpg',
		bgColor: false,
		useDivider: false,
	},
];
